/**
 * Generate the server-native JSX type surface from pinned, vendored data.
 *
 * This command is deliberately offline. Refreshing source data is a separate,
 * reviewable operation handled by `update_jsx_type_sources.ts`.
 */

import sourceData from "./jsx-types/source-data.json" with { type: "json" };

type ElementRecord = {
  readonly name: string;
  readonly interface?: string;
  readonly href: string;
  readonly obsolete: boolean;
  readonly source: string;
};

type AttributeMap = Readonly<Record<string, readonly string[]>>;

type SourceSnapshot = {
  readonly schemaVersion: number;
  readonly provenance: {
    readonly webrefElementsVersion: string;
    readonly webrefIdlVersion: string;
    readonly ariaCommit: string;
  };
  readonly html: {
    readonly spec: { readonly title: string; readonly url: string };
    readonly elements: readonly ElementRecord[];
    readonly attributes: AttributeMap;
  };
  readonly svg: {
    readonly elements: readonly ElementRecord[];
    readonly attributes: AttributeMap;
  };
  readonly aria: {
    readonly specification: string;
    readonly attributes: readonly string[];
    readonly roles: readonly {
      readonly name: string;
      readonly abstract: boolean;
    }[];
  };
};

const snapshot = sourceData as SourceSnapshot;
const outputUrl = new URL("../src/jsx_types.ts", import.meta.url);

async function main(): Promise<void> {
  const args = new Set(Deno.args);
  if (
    args.size > 1 ||
    (args.size === 1 && !args.has("--check"))
  ) {
    throw new Error("Usage: generate_jsx_types.ts [--check]");
  }

  const generated = generateJsxTypes(snapshot);
  if (args.has("--check")) {
    const checkedIn = await Deno.readTextFile(outputUrl);
    if (checkedIn !== generated) {
      throw new Error(
        "src/jsx_types.ts is out of date. Run " +
          "`deno run --allow-write=src/jsx_types.ts " +
          "tools/generate_jsx_types.ts`.",
      );
    }
    console.log("src/jsx_types.ts matches the pinned JSX type sources.");
  } else {
    await Deno.writeTextFile(outputUrl, generated);
    console.log(`Generated ${outputUrl.pathname}`);
  }
}

/** Generate the complete JSX type module from a normalized source snapshot. */
export function generateJsxTypes(data: SourceSnapshot): string {
  validateSnapshot(data);

  const htmlAttributes = cloneAttributeMap(data.html.attributes);
  const svgAttributes = cloneAttributeMap(data.svg.attributes);
  applyHtmlPolicy(htmlAttributes);
  applySvgPolicy(svgAttributes);

  const htmlGlobal = new Set(htmlAttributes["*"] ?? []);
  const svgGlobal = new Set(svgAttributes["*"] ?? []);
  const currentHtmlCount =
    data.html.elements.filter((element) => !element.obsolete).length;
  const obsoleteHtmlCount = data.html.elements.length - currentHtmlCount;
  const concreteRoles = data.aria.roles
    .filter((role) => !role.abstract)
    .map((role) => role.name);

  const lines: string[] = [
    "// This file is generated by tools/generate_jsx_types.ts. Do not edit.",
    "// Generation is offline and deterministic from the pinned source snapshot.",
    `// HTML: ${currentHtmlCount} current + ${obsoleteHtmlCount} obsolete elements; SVG: ${data.svg.elements.length} elements.`,
    `// ARIA: ${
      data.aria.attributes.length - 1
    } aria-* attributes + role; ${concreteRoles.length} concrete roles.`,
    "",
    'import type { Html, Renderable } from "./model.ts";',
    "",
    "/** Values accepted by ordinary serializable custom-element attributes. */",
    "export type AttributeValue =",
    "  | string",
    "  | number",
    "  | bigint",
    "  | boolean",
    "  | null",
    "  | undefined;",
    "type HTMLContentEditable =",
    "  | HTMLBooleanishAttribute",
    '  | Omissible<"inherit" | "plaintext-only">;',
    "",
    "type Omissible<Value> = Value | false | null | undefined;",
    "type StringAttribute = Omissible<string>;",
    "type ScalarAttribute = Omissible<string | number | bigint>;",
    "type NumberAttribute = Omissible<number | `${number}`>;",
    "type SVGNumberAttribute = Omissible<string | number>;",
    "type BooleanAttribute = boolean | null | undefined;",
    'type BooleanishAttribute = Omissible<"false" | "true">;',
    "type HTMLBooleanishAttribute =",
    "  | boolean",
    '  | "false"',
    '  | "true"',
    "  | null",
    "  | undefined;",
    "",
    renderLiteralUnion("CrossOrigin", ["", "anonymous", "use-credentials"]),
    renderLiteralUnion("FetchPriority", ["auto", "high", "low"]),
    renderLiteralUnion("ReferrerPolicy", [
      "",
      "no-referrer",
      "no-referrer-when-downgrade",
      "origin",
      "origin-when-cross-origin",
      "same-origin",
      "strict-origin",
      "strict-origin-when-cross-origin",
      "unsafe-url",
    ]),
    renderLiteralUnion("HTMLInputMode", [
      "decimal",
      "email",
      "none",
      "numeric",
      "search",
      "tel",
      "text",
      "url",
    ]),
    renderLiteralUnion("HTMLEnterKeyHint", [
      "done",
      "enter",
      "go",
      "next",
      "previous",
      "search",
      "send",
    ]),
    renderLiteralUnion("HTMLAutoCapitalize", [
      "characters",
      "none",
      "off",
      "on",
      "sentences",
      "words",
    ]),
    renderLiteralUnion("FormEncoding", [
      "application/x-www-form-urlencoded",
      "multipart/form-data",
      "text/plain",
    ]),
    renderLiteralUnion("HTMLInputType", [
      "button",
      "checkbox",
      "color",
      "date",
      "datetime-local",
      "email",
      "file",
      "hidden",
      "image",
      "month",
      "number",
      "password",
      "radio",
      "range",
      "reset",
      "search",
      "submit",
      "tel",
      "text",
      "time",
      "url",
      "week",
    ]),
    renderLiteralUnion("TrackKind", [
      "captions",
      "chapters",
      "descriptions",
      "metadata",
      "subtitles",
    ]),
    renderLiteralUnion("AriaCurrent", [
      "date",
      "false",
      "location",
      "page",
      "step",
      "time",
      "true",
    ]),
    renderLiteralUnion("AriaHasPopup", [
      "dialog",
      "false",
      "grid",
      "listbox",
      "menu",
      "tree",
      "true",
    ]),
    'type AriaRelevantToken = "additions" | "removals" | "text";',
    "type AriaRelevant =",
    "  | AriaRelevantToken",
    '  | "all"',
    "  | `${AriaRelevantToken} ${string}`;",
    "",
    renderLiteralUnion("AriaRole", concreteRoles),
    "type AriaRoleAttribute = Omissible<",
    "  | AriaRole",
    "  | `${AriaRole} ${string}`",
    "  | `${string}-${string}`",
    ">;",
    "",
    "/** Custom `data-*` attributes accepted by every element. */",
    "export interface DataAttributes {",
    "  [name: `data-${string}`]: AttributeValue;",
    "}",
    "",
    "/** WAI-ARIA 1.3 attributes and concrete role tokens. */",
    "export interface AriaAttributes {",
    ...data.aria.attributes.map((attribute) =>
      `  ${propertyName(attribute)}?: ${ariaAttributeType(attribute)};`
    ),
    "}",
    "",
    "/** Attributes shared by HTML elements. Event handlers are absent. */",
    "export interface HTMLAttributes extends DataAttributes, AriaAttributes {",
    "  children?: Renderable;",
    ...[...htmlGlobal]
      .filter((attribute) =>
        attribute !== "role" && !attribute.startsWith("aria-")
      )
      .sort(compareStrings)
      .map((attribute) =>
        `  ${propertyName(attribute)}?: ${htmlAttributeType("*", attribute)};`
      ),
    "}",
    "",
  ];

  const htmlTypes = new Map<string, string>();
  for (const element of data.html.elements) {
    const attributes = (htmlAttributes[element.name] ?? [])
      .filter((attribute) => !htmlGlobal.has(attribute))
      .sort(compareStrings);
    if (attributes.length === 0) {
      htmlTypes.set(element.name, "HTMLAttributes");
      continue;
    }

    const interfaceName = `HTML${pascalCase(element.name)}Attributes`;
    htmlTypes.set(element.name, interfaceName);
    lines.push(
      "/**",
      ` * Attributes for the HTML \`${element.name}\` element.`,
      ` * @see ${element.href}`,
      ...(element.obsolete
        ? [" * @deprecated This HTML element is obsolete."]
        : []),
      " */",
      `export interface ${interfaceName} extends HTMLAttributes {`,
      ...attributes.map((attribute) =>
        `  ${propertyName(attribute)}?: ${
          htmlAttributeType(element.name, attribute)
        };`
      ),
      "}",
      "",
    );
  }

  lines.push(
    "/**",
    " * Attributes shared by SVG elements, using serialized case-sensitive",
    " * names. Event handlers and React aliases are absent.",
    " */",
    "export interface SVGAttributes extends DataAttributes, AriaAttributes {",
    "  children?: Renderable;",
    ...[...svgGlobal]
      .filter((attribute) =>
        attribute !== "role" && !attribute.startsWith("aria-")
      )
      .sort(compareStrings)
      .map((attribute) =>
        `  ${propertyName(attribute)}?: ${svgAttributeType(attribute)};`
      ),
    "}",
    "",
  );

  const svgTypes = new Map<string, string>();
  for (const element of data.svg.elements) {
    const attributes = (svgAttributes[element.name] ?? [])
      .filter((attribute) => !svgGlobal.has(attribute))
      .sort(compareStrings);
    if (attributes.length === 0) {
      svgTypes.set(element.name, "SVGAttributes");
      continue;
    }

    const interfaceName = `SVG${pascalCase(element.name)}Attributes`;
    svgTypes.set(element.name, interfaceName);
    lines.push(
      "/**",
      ` * Attributes for the SVG \`${element.name}\` element.`,
      ` * @see ${element.href}`,
      " */",
      `export interface ${interfaceName} extends SVGAttributes {`,
      ...attributes.map((attribute) =>
        `  ${propertyName(attribute)}?: ${svgAttributeType(attribute)};`
      ),
      "}",
      "",
    );
  }

  lines.push(
    "/** Serializable props accepted by hyphenated custom-element names. */",
    "export interface CustomElementAttributes extends HTMLAttributes {",
    "  [name: `${string}-${string}`]: AttributeValue;",
    "}",
    "",
    "/**",
    " * Types consumed internally by TypeScript's automatic JSX transform.",
    " *",
    " * @internal",
    " */",
    "// deno-lint-ignore no-namespace",
    "export namespace JSX {",
    "  /** The immutable instruction value produced by a JSX expression. */",
    "  export type Element = Html;",
    "",
    "  /** Intrinsic names and server component functions accepted in JSX. */",
    "  export type ElementType =",
    "    | keyof IntrinsicElements",
    "    | ((props: never) => Renderable);",
    "",
    "  /** Identifies the component prop that receives nested JSX children. */",
    "  export interface ElementChildrenAttribute {",
    "    /** Property used by the transform for nested JSX children. */",
    "    children: unknown;",
    "  }",
    "",
    "  /** HTML, SVG, and custom elements supported by the JSX runtime. */",
    "  export interface IntrinsicElements {",
    "    [tagName: `${string}-${string}`]: CustomElementAttributes;",
    "    // A JSX tag cannot select types from its parent namespace. Names shared",
    "    // by HTML and SVG therefore accept the attributes of either element.",
  );

  const htmlByName = new Map(
    data.html.elements.map((element) => [element.name, element]),
  );
  const svgByName = new Map(
    data.svg.elements.map((element) => [element.name, element]),
  );
  const tagNames = new Set([...htmlByName.keys(), ...svgByName.keys()]);
  for (const tagName of [...tagNames].sort(compareStrings)) {
    const htmlElement = htmlByName.get(tagName);
    const svgElement = svgByName.get(tagName);
    if (htmlElement?.obsolete) {
      lines.push(
        "    /**",
        "     * @deprecated Obsolete HTML element retained for migration.",
        `     * @see ${htmlElement.href}`,
        "     */",
      );
    }

    const types = [
      htmlElement ? htmlTypes.get(tagName) : undefined,
      svgElement ? svgTypes.get(tagName) : undefined,
    ].filter((value): value is string => value !== undefined);
    lines.push(`    ${tagName}: ${types.join(" | ")};`);
  }

  lines.push(
    "  }",
    "}",
    "",
    "/** Props accepted by an intrinsic HTML, SVG, or custom-element tag. */",
    "export type IntrinsicElementProps<",
    "  TagName extends keyof JSX.IntrinsicElements,",
    "> = JSX.IntrinsicElements[TagName];",
    "",
    "/**",
    " * Serializable attributes for a custom element.",
    " *",
    " * Use this while augmenting the `JSX.IntrinsicElements` interface in",
    " * `@bastianplsfix/html/jsx-runtime`. Function, object, symbol, and",
    " * inline-event values become `never`, so augmentation cannot weaken",
    " * runtime validation.",
    " *",
    " * @example",
    " * ```ts",
    ' * import type { CustomElementProps } from "@bastianplsfix/html";',
    " *",
    ' * declare module "@bastianplsfix/html/jsx-runtime" {',
    " *   namespace JSX {",
    " *     interface IntrinsicElements {",
    ' *       "status-pill": CustomElementProps<{',
    ' *         variant?: "neutral" | "success";',
    " *       }>;",
    " *     }",
    " *   }",
    " * }",
    " * ```",
    " */",
    "export type CustomElementProps<Props extends object> =",
    '  & IntrinsicElementProps<"div">',
    "  & { [Name: `${string}-${string}`]: AttributeValue }",
    "  & {",
    '    readonly [Name in keyof Props]: Name extends "children"',
    "      ? Props[Name] extends Renderable ? Props[Name] : never",
    "      : Name extends string",
    '        ? Lowercase<Name> extends `on${string}` | "srcdoc" ? never',
    "        : Props[Name] extends AttributeValue ? Props[Name]",
    "        : never",
    "      : never;",
    "  };",
    "",
  );
  return lines.join("\n");
}

function validateSnapshot(data: SourceSnapshot): void {
  if (data.schemaVersion !== 1) {
    throw new Error(`Unsupported JSX source schema ${data.schemaVersion}.`);
  }
  validateSortedUnique(
    "HTML elements",
    data.html.elements.map((element) => element.name),
  );
  validateSortedUnique(
    "SVG elements",
    data.svg.elements.map((element) => element.name),
  );
  validateSortedUnique("ARIA attributes", data.aria.attributes);
  validateSortedUnique(
    "ARIA roles",
    data.aria.roles.map((role) => role.name),
  );
  for (
    const [element, attributes] of [
      ...Object.entries(data.html.attributes),
      ...Object.entries(data.svg.attributes),
    ]
  ) {
    validateSortedUnique(`attributes for ${element}`, attributes);
  }
  for (const attribute of data.aria.attributes) ariaAttributeType(attribute);
}

function validateSortedUnique(label: string, values: readonly string[]): void {
  const sorted = [...new Set(values)].sort(compareStrings);
  if (JSON.stringify(values) !== JSON.stringify(sorted)) {
    throw new Error(`${label} must be sorted and unique.`);
  }
}

function cloneAttributeMap(source: AttributeMap): Record<string, string[]> {
  return Object.fromEntries(
    Object.entries(source).map((
      [element, attributes],
    ) => [element, [...attributes]]),
  );
}

function applyHtmlPolicy(attributes: Record<string, string[]>): void {
  // Post-snapshot additions from web-platform specifications. The applicability
  // package intentionally updates less often than the platform surface.
  // https://wicg.github.io/attribution-reporting-api/
  addAttributes(attributes, ["a", "area", "img", "script"], ["attributionsrc"]);
  // https://wicg.github.io/anonymous-iframe/#attr-iframe-credentialless
  addAttributes(attributes, ["iframe"], ["credentialless"]);
  // https://www.w3.org/TR/html-media-capture/#the-capture-attribute
  addAttributes(attributes, ["input"], ["capture"]);
  // https://wicg.github.io/controls-list/
  addAttributes(attributes, ["audio", "video"], ["controlslist"]);
  // https://www.w3.org/TR/remote-playback/#disabling-remote-playback
  addAttributes(attributes, ["audio", "video"], ["disableremoteplayback"]);
  // https://html.spec.whatwg.org/multipage/forms.html#attr-form-rel
  addAttributes(attributes, ["form"], ["rel"]);
  // https://html.spec.whatwg.org/multipage/semantics.html#attr-html-xmlns
  addAttributes(attributes, ["html"], ["xmlns"]);

  // `srcdoc` creates a nested HTML parsing context. The renderer intentionally
  // rejects it until it can provide a context-specific safe value API.
  attributes.iframe = (attributes.iframe ?? []).filter((name) =>
    name !== "srcdoc"
  );
  filterUnsafeEventAttributes(attributes);
  sortAttributeMap(attributes);
}

function applySvgPolicy(attributes: Record<string, string[]>): void {
  // SVG 2 retains namespaced XML attributes and defines deprecated XLink
  // compatibility spellings. These are absent from the applicability package.
  // https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs
  addAttributes(attributes, ["*"], ["xml:base", "xml:lang", "xml:space"]);
  addAttributes(attributes, ["svg"], ["xmlns", "xmlns:xlink"]);
  addAttributes(attributes, ["a"], [
    "xlink:actuate",
    "xlink:arcrole",
    "xlink:href",
    "xlink:role",
    "xlink:show",
    "xlink:title",
    "xlink:type",
  ]);
  addAttributes(
    attributes,
    [
      "animate",
      "animateMotion",
      "image",
      "linearGradient",
      "mpath",
      "pattern",
      "radialGradient",
      "script",
      "textPath",
      "use",
    ],
    ["xlink:href"],
  );
  filterUnsafeEventAttributes(attributes);
  sortAttributeMap(attributes);
}

function addAttributes(
  map: Record<string, string[]>,
  elements: readonly string[],
  additions: readonly string[],
): void {
  for (const element of elements) {
    map[element] = [...new Set([...(map[element] ?? []), ...additions])];
  }
}

function filterUnsafeEventAttributes(map: Record<string, string[]>): void {
  for (const [element, attributes] of Object.entries(map)) {
    map[element] = attributes.filter((name) => !/^on/i.test(name));
  }
}

function sortAttributeMap(map: Record<string, string[]>): void {
  for (const attributes of Object.values(map)) attributes.sort(compareStrings);
}

const booleanHtmlAttributes = new Set([
  "allowpaymentrequest",
  "allowfullscreen",
  "allowusermedia",
  "alpha",
  "async",
  "autofocus",
  "autoplay",
  "checked",
  "compact",
  "controls",
  "credentialless",
  "declare",
  "default",
  "defer",
  "disabled",
  "disableremoteplayback",
  "formnovalidate",
  "inert",
  "ismap",
  "itemscope",
  "loop",
  "multiple",
  "muted",
  "nohref",
  "nomodule",
  "noresize",
  "noshade",
  "novalidate",
  "nowrap",
  "open",
  "playsinline",
  "readonly",
  "required",
  "reversed",
  "selected",
  "shadowrootclonable",
  "shadowrootcustomelementregistry",
  "shadowrootdelegatesfocus",
  "shadowrootserializable",
  "truespeed",
  "typemustmatch",
]);

const numericHtmlAttributes = new Set([
  "cols",
  "colspan",
  "height",
  "high",
  "hspace",
  "low",
  "marginheight",
  "marginwidth",
  "maxlength",
  "minlength",
  "optimum",
  "rows",
  "rowspan",
  "size",
  "span",
  "start",
  "tabindex",
  "vspace",
  "width",
]);

const htmlTypeOverrides = new Map<string, string>([
  [
    "*.autocapitalize",
    "Omissible<HTMLAutoCapitalize>",
  ],
  ["*.autocorrect", 'Omissible<"off" | "on">'],
  [
    "*.contenteditable",
    "HTMLContentEditable",
  ],
  ["*.dir", 'Omissible<"auto" | "ltr" | "rtl">'],
  ["*.draggable", "HTMLBooleanishAttribute"],
  ["*.enterkeyhint", "Omissible<HTMLEnterKeyHint>"],
  ["*.hidden", 'BooleanAttribute | "until-found"'],
  ["*.inputmode", "Omissible<HTMLInputMode>"],
  ["*.popover", 'Omissible<"" | "auto" | "hint" | "manual">'],
  ["*.spellcheck", "HTMLBooleanishAttribute"],
  ["*.translate", 'Omissible<"no" | "yes">'],
  ["*.virtualkeyboardpolicy", 'Omissible<"auto" | "manual">'],
  ["*.writingsuggestions", "HTMLBooleanishAttribute"],
  ["a.download", "StringAttribute | BooleanAttribute"],
  ["area.download", "StringAttribute | BooleanAttribute"],
  ["area.shape", 'Omissible<"circle" | "default" | "poly" | "rect">'],
  ["audio.preload", 'Omissible<"" | "auto" | "metadata" | "none">'],
  [
    "button.formenctype",
    "Omissible<FormEncoding>",
  ],
  ["button.formmethod", 'Omissible<"dialog" | "get" | "post">'],
  ["button.popovertargetaction", 'Omissible<"hide" | "show" | "toggle">'],
  ["button.type", 'Omissible<"button" | "reset" | "submit">'],
  ["dialog.closedby", 'Omissible<"any" | "closerequest" | "none">'],
  ["form.autocomplete", 'Omissible<"off" | "on">'],
  [
    "form.enctype",
    "Omissible<FormEncoding>",
  ],
  ["form.method", 'Omissible<"dialog" | "get" | "post">'],
  ["iframe.loading", 'Omissible<"eager" | "lazy">'],
  ["img.decoding", 'Omissible<"async" | "auto" | "sync">'],
  ["img.loading", 'Omissible<"eager" | "lazy">'],
  ["input.capture", 'BooleanAttribute | Omissible<"environment" | "user">'],
  ["input.colorspace", 'Omissible<"display-p3" | "limited-srgb">'],
  [
    "input.formenctype",
    "Omissible<FormEncoding>",
  ],
  ["input.formmethod", 'Omissible<"dialog" | "get" | "post">'],
  ["input.popovertargetaction", 'Omissible<"hide" | "show" | "toggle">'],
  [
    "input.type",
    "Omissible<HTMLInputType>",
  ],
  ["link.fetchpriority", "Omissible<FetchPriority>"],
  ["ol.type", 'Omissible<"1" | "A" | "I" | "a" | "i">'],
  ["script.fetchpriority", "Omissible<FetchPriority>"],
  ["td.scope", 'Omissible<"col" | "colgroup" | "row" | "rowgroup">'],
  ["textarea.wrap", 'Omissible<"hard" | "soft">'],
  ["template.shadowrootmode", 'Omissible<"closed" | "open">'],
  ["th.scope", 'Omissible<"col" | "colgroup" | "row" | "rowgroup">'],
  [
    "track.kind",
    "Omissible<TrackKind>",
  ],
  ["video.preload", 'Omissible<"" | "auto" | "metadata" | "none">'],
]);

function htmlAttributeType(element: string, attribute: string): string {
  const override = htmlTypeOverrides.get(`${element}.${attribute}`) ??
    htmlTypeOverrides.get(`*.${attribute}`);
  if (override) return override;
  if (booleanHtmlAttributes.has(attribute)) return "BooleanAttribute";
  if (numericHtmlAttributes.has(attribute)) return "NumberAttribute";
  if (attribute === "crossorigin") return "Omissible<CrossOrigin>";
  if (attribute === "fetchpriority") return "Omissible<FetchPriority>";
  if (attribute === "referrerpolicy") return "Omissible<ReferrerPolicy>";
  if (attribute === "value") return "ScalarAttribute";
  if (["max", "min", "step"].includes(attribute)) return "ScalarAttribute";
  return "StringAttribute";
}

function ariaAttributeType(attribute: string): string {
  if (attribute === "role") return "AriaRoleAttribute";
  if (
    [
      "aria-atomic",
      "aria-busy",
      "aria-disabled",
      "aria-modal",
      "aria-multiline",
      "aria-multiselectable",
      "aria-readonly",
      "aria-required",
    ].includes(attribute)
  ) return "BooleanishAttribute";
  if (["aria-checked", "aria-pressed"].includes(attribute)) {
    return 'Omissible<"false" | "mixed" | "true" | "undefined">';
  }
  if (["aria-expanded", "aria-hidden", "aria-selected"].includes(attribute)) {
    return 'Omissible<"false" | "true" | "undefined">';
  }
  if (
    [
      "aria-colcount",
      "aria-colindex",
      "aria-colspan",
      "aria-level",
      "aria-posinset",
      "aria-rowcount",
      "aria-rowindex",
      "aria-rowspan",
      "aria-setsize",
      "aria-valuemax",
      "aria-valuemin",
      "aria-valuenow",
    ].includes(attribute)
  ) return "NumberAttribute";

  const enumerated = new Map<string, readonly string[]>([
    ["aria-autocomplete", ["both", "inline", "list", "none"]],
    ["aria-invalid", ["false", "grammar", "spelling", "true"]],
    ["aria-live", ["assertive", "off", "polite"]],
    ["aria-orientation", ["horizontal", "undefined", "vertical"]],
    ["aria-sort", ["ascending", "descending", "none", "other"]],
  ]);
  if (attribute === "aria-current") return "Omissible<AriaCurrent>";
  if (attribute === "aria-haspopup") return "Omissible<AriaHasPopup>";
  const values = enumerated.get(attribute);
  if (values) return `Omissible<${values.map(quote).join(" | ")}>`;
  if (attribute === "aria-relevant") {
    return "Omissible<AriaRelevant>";
  }
  if (!attribute.startsWith("aria-")) {
    throw new Error(`Unknown ARIA attribute ${attribute}.`);
  }
  return "StringAttribute";
}

const numericSvgAttributes = new Set([
  "amplitude",
  "azimuth",
  "baseFrequency",
  "baseline-shift",
  "begin",
  "bias",
  "by",
  "cx",
  "cy",
  "decelerate",
  "diffuseConstant",
  "divisor",
  "dur",
  "dx",
  "dy",
  "elevation",
  "end",
  "exponent",
  "fill-opacity",
  "flood-opacity",
  "font-size",
  "font-size-adjust",
  "font-weight",
  "fr",
  "from",
  "fx",
  "fy",
  "height",
  "intercept",
  "k1",
  "k2",
  "k3",
  "k4",
  "kernelUnitLength",
  "letter-spacing",
  "limitingConeAngle",
  "markerHeight",
  "markerWidth",
  "max",
  "min",
  "numOctaves",
  "offset",
  "opacity",
  "order",
  "origin",
  "pathLength",
  "pointsAtX",
  "pointsAtY",
  "pointsAtZ",
  "r",
  "radius",
  "refX",
  "refY",
  "rotate",
  "rx",
  "ry",
  "scale",
  "seed",
  "slope",
  "specularConstant",
  "specularExponent",
  "startOffset",
  "stdDeviation",
  "stop-opacity",
  "stroke-dasharray",
  "stroke-dashoffset",
  "stroke-miterlimit",
  "stroke-opacity",
  "stroke-width",
  "surfaceScale",
  "targetX",
  "targetY",
  "textLength",
  "to",
  "width",
  "word-spacing",
  "x",
  "x1",
  "x2",
  "y",
  "y1",
  "y2",
  "z",
]);

const svgTypeOverrides = new Map<string, string>([
  ["accumulate", 'Omissible<"none" | "sum">'],
  ["additive", 'Omissible<"replace" | "sum">'],
  ["calcMode", 'Omissible<"discrete" | "linear" | "paced" | "spline">'],
  ["clip-rule", 'Omissible<"evenodd" | "inherit" | "nonzero">'],
  ["color-interpolation-filters", 'Omissible<"auto" | "linearRGB" | "sRGB">'],
  ["crossorigin", "Omissible<CrossOrigin>"],
  ["edgeMode", 'Omissible<"duplicate" | "none" | "wrap">'],
  ["externalResourcesRequired", "BooleanishAttribute"],
  ["fill-rule", 'Omissible<"evenodd" | "inherit" | "nonzero">'],
  ["filterUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["focusable", 'Omissible<"auto" | "false" | "true">'],
  ["gradientUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["lengthAdjust", 'Omissible<"spacing" | "spacingAndGlyphs">'],
  ["markerUnits", 'Omissible<"strokeWidth" | "userSpaceOnUse">'],
  ["maskContentUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["maskUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  [
    "orient",
    'SVGNumberAttribute | Omissible<"auto" | "auto-start-reverse">',
  ],
  ["patternContentUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["patternUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["preserveAlpha", "BooleanishAttribute"],
  ["primitiveUnits", 'Omissible<"objectBoundingBox" | "userSpaceOnUse">'],
  ["referrerpolicy", "Omissible<ReferrerPolicy>"],
  ["repeatCount", 'SVGNumberAttribute | Omissible<"indefinite">'],
  ["repeatDur", 'SVGNumberAttribute | Omissible<"indefinite">'],
  ["restart", 'Omissible<"always" | "never" | "whenNotActive">'],
  ["spacing", 'Omissible<"auto" | "exact">'],
  ["spreadMethod", 'Omissible<"pad" | "reflect" | "repeat">'],
  ["stitchTiles", 'Omissible<"noStitch" | "stitch">'],
  ["stroke-linecap", 'Omissible<"butt" | "inherit" | "round" | "square">'],
  ["stroke-linejoin", 'Omissible<"bevel" | "inherit" | "miter" | "round">'],
  ["text-anchor", 'Omissible<"end" | "inherit" | "middle" | "start">'],
  ["xChannelSelector", 'Omissible<"A" | "B" | "G" | "R">'],
  ["xml:space", 'Omissible<"default" | "preserve">'],
  ["yChannelSelector", 'Omissible<"A" | "B" | "G" | "R">'],
  ["zoomAndPan", 'Omissible<"disable" | "magnify">'],
]);

function svgAttributeType(attribute: string): string {
  const override = svgTypeOverrides.get(attribute);
  if (override) return override;
  if (numericSvgAttributes.has(attribute)) return "SVGNumberAttribute";
  return "StringAttribute";
}

function renderLiteralUnion(name: string, values: readonly string[]): string {
  return [
    `type ${name} =`,
    ...values.map((value, index) =>
      `  | ${quote(value)}${index === values.length - 1 ? ";" : ""}`
    ),
    "",
  ].join("\n");
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : quote(name);
}

function pascalCase(name: string): string {
  return name[0].toUpperCase() + name.slice(1);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

if (import.meta.main) await main();
