// This file is generated by tools/generate_jsx_types.ts. Do not edit.
// Generation is offline and deterministic from the pinned source snapshot.
// HTML: 113 current + 29 obsolete elements; SVG: 63 elements.
// ARIA: 51 aria-* attributes + role; 88 concrete roles.

import type { Html, Renderable } from "./model.ts";

/** Values accepted by ordinary serializable custom-element attributes. */
export type AttributeValue =
  | string
  | number
  | bigint
  | boolean
  | null
  | undefined;
type HTMLContentEditable =
  | HTMLBooleanishAttribute
  | Omissible<"inherit" | "plaintext-only">;

type Omissible<Value> = Value | false | null | undefined;
type StringAttribute = Omissible<string>;
type ScalarAttribute = Omissible<string | number | bigint>;
type NumberAttribute = Omissible<number | `${number}`>;
type SVGNumberAttribute = Omissible<string | number>;
type BooleanAttribute = boolean | null | undefined;
type BooleanishAttribute = Omissible<"false" | "true">;
type HTMLBooleanishAttribute =
  | boolean
  | "false"
  | "true"
  | null
  | undefined;

type CrossOrigin =
  | ""
  | "anonymous"
  | "use-credentials";

type FetchPriority =
  | "auto"
  | "high"
  | "low";

type ReferrerPolicy =
  | ""
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";

type HTMLInputMode =
  | "decimal"
  | "email"
  | "none"
  | "numeric"
  | "search"
  | "tel"
  | "text"
  | "url";

type HTMLEnterKeyHint =
  | "done"
  | "enter"
  | "go"
  | "next"
  | "previous"
  | "search"
  | "send";

type HTMLAutoCapitalize =
  | "characters"
  | "none"
  | "off"
  | "on"
  | "sentences"
  | "words";

type FormEncoding =
  | "application/x-www-form-urlencoded"
  | "multipart/form-data"
  | "text/plain";

type HTMLInputType =
  | "button"
  | "checkbox"
  | "color"
  | "date"
  | "datetime-local"
  | "email"
  | "file"
  | "hidden"
  | "image"
  | "month"
  | "number"
  | "password"
  | "radio"
  | "range"
  | "reset"
  | "search"
  | "submit"
  | "tel"
  | "text"
  | "time"
  | "url"
  | "week";

type TrackKind =
  | "captions"
  | "chapters"
  | "descriptions"
  | "metadata"
  | "subtitles";

type AriaCurrent =
  | "date"
  | "false"
  | "location"
  | "page"
  | "step"
  | "time"
  | "true";

type AriaHasPopup =
  | "dialog"
  | "false"
  | "grid"
  | "listbox"
  | "menu"
  | "tree"
  | "true";

type AriaRelevantToken = "additions" | "removals" | "text";
type AriaRelevant =
  | AriaRelevantToken
  | "all"
  | `${AriaRelevantToken} ${string}`;

type AriaRole =
  | "alert"
  | "alertdialog"
  | "application"
  | "article"
  | "banner"
  | "blockquote"
  | "button"
  | "caption"
  | "cell"
  | "checkbox"
  | "code"
  | "columnheader"
  | "combobox"
  | "comment"
  | "complementary"
  | "contentinfo"
  | "definition"
  | "deletion"
  | "dialog"
  | "directory"
  | "document"
  | "emphasis"
  | "feed"
  | "figure"
  | "form"
  | "generic"
  | "grid"
  | "gridcell"
  | "group"
  | "heading"
  | "image"
  | "img"
  | "insertion"
  | "link"
  | "list"
  | "listbox"
  | "listitem"
  | "log"
  | "main"
  | "mark"
  | "marquee"
  | "math"
  | "menu"
  | "menubar"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "meter"
  | "navigation"
  | "none"
  | "note"
  | "option"
  | "paragraph"
  | "presentation"
  | "progressbar"
  | "radio"
  | "radiogroup"
  | "region"
  | "row"
  | "rowgroup"
  | "rowheader"
  | "scrollbar"
  | "search"
  | "searchbox"
  | "sectionfooter"
  | "sectionheader"
  | "separator"
  | "slider"
  | "spinbutton"
  | "status"
  | "strong"
  | "subscript"
  | "suggestion"
  | "superscript"
  | "switch"
  | "tab"
  | "table"
  | "tablist"
  | "tabpanel"
  | "term"
  | "textbox"
  | "time"
  | "timer"
  | "toolbar"
  | "tooltip"
  | "tree"
  | "treegrid"
  | "treeitem";

type AriaRoleAttribute = Omissible<
  | AriaRole
  | `${AriaRole} ${string}`
  | `${string}-${string}`
>;

/** Custom `data-*` attributes accepted by every element. */
export interface DataAttributes {
  [name: `data-${string}`]: AttributeValue;
}

/** WAI-ARIA 1.3 attributes and concrete role tokens. */
export interface AriaAttributes {
  "aria-activedescendant"?: StringAttribute;
  "aria-atomic"?: BooleanishAttribute;
  "aria-autocomplete"?: Omissible<"both" | "inline" | "list" | "none">;
  "aria-braillelabel"?: StringAttribute;
  "aria-brailleroledescription"?: StringAttribute;
  "aria-busy"?: BooleanishAttribute;
  "aria-checked"?: Omissible<"false" | "mixed" | "true" | "undefined">;
  "aria-colcount"?: NumberAttribute;
  "aria-colindex"?: NumberAttribute;
  "aria-colindextext"?: StringAttribute;
  "aria-colspan"?: NumberAttribute;
  "aria-controls"?: StringAttribute;
  "aria-current"?: Omissible<AriaCurrent>;
  "aria-describedby"?: StringAttribute;
  "aria-description"?: StringAttribute;
  "aria-details"?: StringAttribute;
  "aria-disabled"?: BooleanishAttribute;
  "aria-errormessage"?: StringAttribute;
  "aria-expanded"?: Omissible<"false" | "true" | "undefined">;
  "aria-flowto"?: StringAttribute;
  "aria-haspopup"?: Omissible<AriaHasPopup>;
  "aria-hidden"?: Omissible<"false" | "true" | "undefined">;
  "aria-invalid"?: Omissible<"false" | "grammar" | "spelling" | "true">;
  "aria-keyshortcuts"?: StringAttribute;
  "aria-label"?: StringAttribute;
  "aria-labelledby"?: StringAttribute;
  "aria-level"?: NumberAttribute;
  "aria-live"?: Omissible<"assertive" | "off" | "polite">;
  "aria-modal"?: BooleanishAttribute;
  "aria-multiline"?: BooleanishAttribute;
  "aria-multiselectable"?: BooleanishAttribute;
  "aria-orientation"?: Omissible<"horizontal" | "undefined" | "vertical">;
  "aria-owns"?: StringAttribute;
  "aria-placeholder"?: StringAttribute;
  "aria-posinset"?: NumberAttribute;
  "aria-pressed"?: Omissible<"false" | "mixed" | "true" | "undefined">;
  "aria-readonly"?: BooleanishAttribute;
  "aria-relevant"?: Omissible<AriaRelevant>;
  "aria-required"?: BooleanishAttribute;
  "aria-roledescription"?: StringAttribute;
  "aria-rowcount"?: NumberAttribute;
  "aria-rowindex"?: NumberAttribute;
  "aria-rowindextext"?: StringAttribute;
  "aria-rowspan"?: NumberAttribute;
  "aria-selected"?: Omissible<"false" | "true" | "undefined">;
  "aria-setsize"?: NumberAttribute;
  "aria-sort"?: Omissible<"ascending" | "descending" | "none" | "other">;
  "aria-valuemax"?: NumberAttribute;
  "aria-valuemin"?: NumberAttribute;
  "aria-valuenow"?: NumberAttribute;
  "aria-valuetext"?: StringAttribute;
  role?: AriaRoleAttribute;
}

/** Attributes shared by HTML elements. Event handlers are absent. */
export interface HTMLAttributes extends DataAttributes, AriaAttributes {
  children?: Renderable;
  accesskey?: StringAttribute;
  autocapitalize?: Omissible<HTMLAutoCapitalize>;
  autocorrect?: Omissible<"off" | "on">;
  autofocus?: BooleanAttribute;
  class?: StringAttribute;
  contenteditable?: HTMLContentEditable;
  dir?: Omissible<"auto" | "ltr" | "rtl">;
  draggable?: HTMLBooleanishAttribute;
  enterkeyhint?: Omissible<HTMLEnterKeyHint>;
  exportparts?: StringAttribute;
  hidden?: BooleanAttribute | "until-found";
  id?: StringAttribute;
  inert?: BooleanAttribute;
  inputmode?: Omissible<HTMLInputMode>;
  is?: StringAttribute;
  itemid?: StringAttribute;
  itemprop?: StringAttribute;
  itemref?: StringAttribute;
  itemscope?: BooleanAttribute;
  itemtype?: StringAttribute;
  lang?: StringAttribute;
  nonce?: StringAttribute;
  part?: StringAttribute;
  popover?: Omissible<"" | "auto" | "hint" | "manual">;
  slot?: StringAttribute;
  spellcheck?: HTMLBooleanishAttribute;
  style?: StringAttribute;
  tabindex?: NumberAttribute;
  title?: StringAttribute;
  translate?: Omissible<"no" | "yes">;
  writingsuggestions?: HTMLBooleanishAttribute;
}

/**
 * Attributes for the HTML `a` element.
 * @see https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
 */
export interface HTMLAAttributes extends HTMLAttributes {
  attributionsrc?: StringAttribute;
  charset?: StringAttribute;
  coords?: StringAttribute;
  download?: StringAttribute | BooleanAttribute;
  href?: StringAttribute;
  hreflang?: StringAttribute;
  name?: StringAttribute;
  ping?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  rel?: StringAttribute;
  rev?: StringAttribute;
  shape?: StringAttribute;
  target?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `applet` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#applet
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLAppletAttributes extends HTMLAttributes {
  align?: StringAttribute;
  alt?: StringAttribute;
  archive?: StringAttribute;
  code?: StringAttribute;
  codebase?: StringAttribute;
  height?: NumberAttribute;
  hspace?: NumberAttribute;
  name?: StringAttribute;
  object?: StringAttribute;
  vspace?: NumberAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `area` element.
 * @see https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element
 */
export interface HTMLAreaAttributes extends HTMLAttributes {
  alt?: StringAttribute;
  attributionsrc?: StringAttribute;
  coords?: StringAttribute;
  download?: StringAttribute | BooleanAttribute;
  href?: StringAttribute;
  hreflang?: StringAttribute;
  nohref?: BooleanAttribute;
  ping?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  rel?: StringAttribute;
  shape?: Omissible<"circle" | "default" | "poly" | "rect">;
  target?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `audio` element.
 * @see https://html.spec.whatwg.org/multipage/media.html#audio
 */
export interface HTMLAudioAttributes extends HTMLAttributes {
  autoplay?: BooleanAttribute;
  controls?: BooleanAttribute;
  controlslist?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  disableremoteplayback?: BooleanAttribute;
  loop?: BooleanAttribute;
  muted?: BooleanAttribute;
  preload?: Omissible<"" | "auto" | "metadata" | "none">;
  src?: StringAttribute;
}

/**
 * Attributes for the HTML `base` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#the-base-element
 */
export interface HTMLBaseAttributes extends HTMLAttributes {
  href?: StringAttribute;
  target?: StringAttribute;
}

/**
 * Attributes for the HTML `basefont` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#basefont
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLBasefontAttributes extends HTMLAttributes {
  color?: StringAttribute;
  face?: StringAttribute;
  size?: NumberAttribute;
}

/**
 * Attributes for the HTML `blockquote` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element
 */
export interface HTMLBlockquoteAttributes extends HTMLAttributes {
  cite?: StringAttribute;
}

/**
 * Attributes for the HTML `body` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-body-element
 */
export interface HTMLBodyAttributes extends HTMLAttributes {
  alink?: StringAttribute;
  background?: StringAttribute;
  bgcolor?: StringAttribute;
  link?: StringAttribute;
  text?: StringAttribute;
  vlink?: StringAttribute;
}

/**
 * Attributes for the HTML `br` element.
 * @see https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element
 */
export interface HTMLBrAttributes extends HTMLAttributes {
  clear?: StringAttribute;
}

/**
 * Attributes for the HTML `button` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element
 */
export interface HTMLButtonAttributes extends HTMLAttributes {
  command?: StringAttribute;
  commandfor?: StringAttribute;
  disabled?: BooleanAttribute;
  form?: StringAttribute;
  formaction?: StringAttribute;
  formenctype?: Omissible<FormEncoding>;
  formmethod?: Omissible<"dialog" | "get" | "post">;
  formnovalidate?: BooleanAttribute;
  formtarget?: StringAttribute;
  name?: StringAttribute;
  popovertarget?: StringAttribute;
  popovertargetaction?: Omissible<"hide" | "show" | "toggle">;
  type?: Omissible<"button" | "reset" | "submit">;
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `canvas` element.
 * @see https://html.spec.whatwg.org/multipage/canvas.html#canvas
 */
export interface HTMLCanvasAttributes extends HTMLAttributes {
  height?: NumberAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `caption` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-caption-element
 */
export interface HTMLCaptionAttributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `col` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-col-element
 */
export interface HTMLColAttributes extends HTMLAttributes {
  align?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  span?: NumberAttribute;
  valign?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `colgroup` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element
 */
export interface HTMLColgroupAttributes extends HTMLAttributes {
  align?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  span?: NumberAttribute;
  valign?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `data` element.
 * @see https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-data-element
 */
export interface HTMLDataAttributes extends HTMLAttributes {
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `del` element.
 * @see https://html.spec.whatwg.org/multipage/edits.html#the-del-element
 */
export interface HTMLDelAttributes extends HTMLAttributes {
  cite?: StringAttribute;
  datetime?: StringAttribute;
}

/**
 * Attributes for the HTML `details` element.
 * @see https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element
 */
export interface HTMLDetailsAttributes extends HTMLAttributes {
  name?: StringAttribute;
  open?: BooleanAttribute;
}

/**
 * Attributes for the HTML `dialog` element.
 * @see https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element
 */
export interface HTMLDialogAttributes extends HTMLAttributes {
  closedby?: Omissible<"any" | "closerequest" | "none">;
  open?: BooleanAttribute;
}

/**
 * Attributes for the HTML `dir` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#dir
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLDirAttributes extends HTMLAttributes {
  compact?: BooleanAttribute;
}

/**
 * Attributes for the HTML `div` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element
 */
export interface HTMLDivAttributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `dl` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element
 */
export interface HTMLDlAttributes extends HTMLAttributes {
  compact?: BooleanAttribute;
}

/**
 * Attributes for the HTML `embed` element.
 * @see https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element
 */
export interface HTMLEmbedAttributes extends HTMLAttributes {
  height?: NumberAttribute;
  src?: StringAttribute;
  type?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `fieldset` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element
 */
export interface HTMLFieldsetAttributes extends HTMLAttributes {
  disabled?: BooleanAttribute;
  form?: StringAttribute;
  name?: StringAttribute;
}

/**
 * Attributes for the HTML `font` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#font
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLFontAttributes extends HTMLAttributes {
  color?: StringAttribute;
  face?: StringAttribute;
  size?: NumberAttribute;
}

/**
 * Attributes for the HTML `form` element.
 * @see https://html.spec.whatwg.org/multipage/forms.html#the-form-element
 */
export interface HTMLFormAttributes extends HTMLAttributes {
  accept?: StringAttribute;
  "accept-charset"?: StringAttribute;
  action?: StringAttribute;
  autocomplete?: Omissible<"off" | "on">;
  enctype?: Omissible<FormEncoding>;
  method?: Omissible<"dialog" | "get" | "post">;
  name?: StringAttribute;
  novalidate?: BooleanAttribute;
  rel?: StringAttribute;
  target?: StringAttribute;
}

/**
 * Attributes for the HTML `frame` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#frame
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLFrameAttributes extends HTMLAttributes {
  frameborder?: StringAttribute;
  longdesc?: StringAttribute;
  marginheight?: NumberAttribute;
  marginwidth?: NumberAttribute;
  name?: StringAttribute;
  noresize?: BooleanAttribute;
  scrolling?: StringAttribute;
  src?: StringAttribute;
}

/**
 * Attributes for the HTML `frameset` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#frameset
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLFramesetAttributes extends HTMLAttributes {
  cols?: NumberAttribute;
  rows?: NumberAttribute;
}

/**
 * Attributes for the HTML `h1` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h1-element
 */
export interface HTMLH1Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `h2` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h2-element
 */
export interface HTMLH2Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `h3` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h3-element
 */
export interface HTMLH3Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `h4` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h4-element
 */
export interface HTMLH4Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `h5` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h5-element
 */
export interface HTMLH5Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `h6` element.
 * @see https://html.spec.whatwg.org/multipage/sections.html#the-h6-element
 */
export interface HTMLH6Attributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `head` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#the-head-element
 */
export interface HTMLHeadAttributes extends HTMLAttributes {
  profile?: StringAttribute;
}

/**
 * Attributes for the HTML `hr` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-hr-element
 */
export interface HTMLHrAttributes extends HTMLAttributes {
  align?: StringAttribute;
  noshade?: BooleanAttribute;
  size?: NumberAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `html` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
 */
export interface HTMLHtmlAttributes extends HTMLAttributes {
  manifest?: StringAttribute;
  version?: StringAttribute;
  xmlns?: StringAttribute;
}

/**
 * Attributes for the HTML `iframe` element.
 * @see https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element
 */
export interface HTMLIframeAttributes extends HTMLAttributes {
  align?: StringAttribute;
  allow?: StringAttribute;
  allowfullscreen?: BooleanAttribute;
  allowpaymentrequest?: BooleanAttribute;
  allowusermedia?: BooleanAttribute;
  credentialless?: BooleanAttribute;
  frameborder?: StringAttribute;
  height?: NumberAttribute;
  loading?: Omissible<"eager" | "lazy">;
  longdesc?: StringAttribute;
  marginheight?: NumberAttribute;
  marginwidth?: NumberAttribute;
  name?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  sandbox?: StringAttribute;
  scrolling?: StringAttribute;
  src?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `img` element.
 * @see https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element
 */
export interface HTMLImgAttributes extends HTMLAttributes {
  align?: StringAttribute;
  alt?: StringAttribute;
  attributionsrc?: StringAttribute;
  border?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  decoding?: Omissible<"async" | "auto" | "sync">;
  fetchpriority?: Omissible<FetchPriority>;
  height?: NumberAttribute;
  hspace?: NumberAttribute;
  ismap?: BooleanAttribute;
  loading?: Omissible<"eager" | "lazy">;
  longdesc?: StringAttribute;
  name?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  sizes?: StringAttribute;
  src?: StringAttribute;
  srcset?: StringAttribute;
  usemap?: StringAttribute;
  vspace?: NumberAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `input` element.
 * @see https://html.spec.whatwg.org/multipage/input.html#the-input-element
 */
export interface HTMLInputAttributes extends HTMLAttributes {
  accept?: StringAttribute;
  align?: StringAttribute;
  alpha?: BooleanAttribute;
  alt?: StringAttribute;
  autocomplete?: StringAttribute;
  capture?: BooleanAttribute | Omissible<"environment" | "user">;
  checked?: BooleanAttribute;
  colorspace?: Omissible<"display-p3" | "limited-srgb">;
  dirname?: StringAttribute;
  disabled?: BooleanAttribute;
  form?: StringAttribute;
  formaction?: StringAttribute;
  formenctype?: Omissible<FormEncoding>;
  formmethod?: Omissible<"dialog" | "get" | "post">;
  formnovalidate?: BooleanAttribute;
  formtarget?: StringAttribute;
  height?: NumberAttribute;
  ismap?: BooleanAttribute;
  list?: StringAttribute;
  max?: ScalarAttribute;
  maxlength?: NumberAttribute;
  min?: ScalarAttribute;
  minlength?: NumberAttribute;
  multiple?: BooleanAttribute;
  name?: StringAttribute;
  pattern?: StringAttribute;
  placeholder?: StringAttribute;
  popovertarget?: StringAttribute;
  popovertargetaction?: Omissible<"hide" | "show" | "toggle">;
  readonly?: BooleanAttribute;
  required?: BooleanAttribute;
  size?: NumberAttribute;
  src?: StringAttribute;
  step?: ScalarAttribute;
  type?: Omissible<HTMLInputType>;
  usemap?: StringAttribute;
  value?: ScalarAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `ins` element.
 * @see https://html.spec.whatwg.org/multipage/edits.html#the-ins-element
 */
export interface HTMLInsAttributes extends HTMLAttributes {
  cite?: StringAttribute;
  datetime?: StringAttribute;
}

/**
 * Attributes for the HTML `isindex` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#isindex
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLIsindexAttributes extends HTMLAttributes {
  prompt?: StringAttribute;
}

/**
 * Attributes for the HTML `label` element.
 * @see https://html.spec.whatwg.org/multipage/forms.html#the-label-element
 */
export interface HTMLLabelAttributes extends HTMLAttributes {
  for?: StringAttribute;
  form?: StringAttribute;
}

/**
 * Attributes for the HTML `legend` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element
 */
export interface HTMLLegendAttributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `li` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element
 */
export interface HTMLLiAttributes extends HTMLAttributes {
  type?: StringAttribute;
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `link` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#the-link-element
 */
export interface HTMLLinkAttributes extends HTMLAttributes {
  as?: StringAttribute;
  blocking?: StringAttribute;
  charset?: StringAttribute;
  color?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  disabled?: BooleanAttribute;
  fetchpriority?: Omissible<FetchPriority>;
  href?: StringAttribute;
  hreflang?: StringAttribute;
  imagesizes?: StringAttribute;
  imagesrcset?: StringAttribute;
  integrity?: StringAttribute;
  media?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  rel?: StringAttribute;
  rev?: StringAttribute;
  sizes?: StringAttribute;
  target?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `map` element.
 * @see https://html.spec.whatwg.org/multipage/image-maps.html#the-map-element
 */
export interface HTMLMapAttributes extends HTMLAttributes {
  name?: StringAttribute;
}

/**
 * Attributes for the HTML `menu` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#menus
 */
export interface HTMLMenuAttributes extends HTMLAttributes {
  compact?: BooleanAttribute;
}

/**
 * Attributes for the HTML `meta` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#meta
 */
export interface HTMLMetaAttributes extends HTMLAttributes {
  charset?: StringAttribute;
  content?: StringAttribute;
  "http-equiv"?: StringAttribute;
  media?: StringAttribute;
  name?: StringAttribute;
  scheme?: StringAttribute;
}

/**
 * Attributes for the HTML `meter` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element
 */
export interface HTMLMeterAttributes extends HTMLAttributes {
  high?: NumberAttribute;
  low?: NumberAttribute;
  max?: ScalarAttribute;
  min?: ScalarAttribute;
  optimum?: NumberAttribute;
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `object` element.
 * @see https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element
 */
export interface HTMLObjectAttributes extends HTMLAttributes {
  align?: StringAttribute;
  archive?: StringAttribute;
  border?: StringAttribute;
  classid?: StringAttribute;
  codebase?: StringAttribute;
  codetype?: StringAttribute;
  data?: StringAttribute;
  declare?: BooleanAttribute;
  form?: StringAttribute;
  height?: NumberAttribute;
  hspace?: NumberAttribute;
  name?: StringAttribute;
  standby?: StringAttribute;
  type?: StringAttribute;
  typemustmatch?: BooleanAttribute;
  usemap?: StringAttribute;
  vspace?: NumberAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `ol` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element
 */
export interface HTMLOlAttributes extends HTMLAttributes {
  compact?: BooleanAttribute;
  reversed?: BooleanAttribute;
  start?: NumberAttribute;
  type?: Omissible<"1" | "A" | "I" | "a" | "i">;
}

/**
 * Attributes for the HTML `optgroup` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-optgroup-element
 */
export interface HTMLOptgroupAttributes extends HTMLAttributes {
  disabled?: BooleanAttribute;
  label?: StringAttribute;
}

/**
 * Attributes for the HTML `option` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element
 */
export interface HTMLOptionAttributes extends HTMLAttributes {
  disabled?: BooleanAttribute;
  label?: StringAttribute;
  selected?: BooleanAttribute;
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `output` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-output-element
 */
export interface HTMLOutputAttributes extends HTMLAttributes {
  for?: StringAttribute;
  form?: StringAttribute;
  name?: StringAttribute;
}

/**
 * Attributes for the HTML `p` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
 */
export interface HTMLPAttributes extends HTMLAttributes {
  align?: StringAttribute;
}

/**
 * Attributes for the HTML `param` element.
 * @see https://html.spec.whatwg.org/multipage/obsolete.html#param
 * @deprecated This HTML element is obsolete.
 */
export interface HTMLParamAttributes extends HTMLAttributes {
  name?: StringAttribute;
  type?: StringAttribute;
  value?: ScalarAttribute;
  valuetype?: StringAttribute;
}

/**
 * Attributes for the HTML `pre` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element
 */
export interface HTMLPreAttributes extends HTMLAttributes {
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `progress` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element
 */
export interface HTMLProgressAttributes extends HTMLAttributes {
  max?: ScalarAttribute;
  value?: ScalarAttribute;
}

/**
 * Attributes for the HTML `q` element.
 * @see https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-q-element
 */
export interface HTMLQAttributes extends HTMLAttributes {
  cite?: StringAttribute;
}

/**
 * Attributes for the HTML `script` element.
 * @see https://html.spec.whatwg.org/multipage/scripting.html#script
 */
export interface HTMLScriptAttributes extends HTMLAttributes {
  async?: BooleanAttribute;
  attributionsrc?: StringAttribute;
  blocking?: StringAttribute;
  charset?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  defer?: BooleanAttribute;
  fetchpriority?: Omissible<FetchPriority>;
  integrity?: StringAttribute;
  language?: StringAttribute;
  nomodule?: BooleanAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  src?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `select` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element
 */
export interface HTMLSelectAttributes extends HTMLAttributes {
  autocomplete?: StringAttribute;
  disabled?: BooleanAttribute;
  form?: StringAttribute;
  multiple?: BooleanAttribute;
  name?: StringAttribute;
  required?: BooleanAttribute;
  size?: NumberAttribute;
}

/**
 * Attributes for the HTML `slot` element.
 * @see https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element
 */
export interface HTMLSlotAttributes extends HTMLAttributes {
  name?: StringAttribute;
}

/**
 * Attributes for the HTML `source` element.
 * @see https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element
 */
export interface HTMLSourceAttributes extends HTMLAttributes {
  height?: NumberAttribute;
  media?: StringAttribute;
  sizes?: StringAttribute;
  src?: StringAttribute;
  srcset?: StringAttribute;
  type?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `style` element.
 * @see https://html.spec.whatwg.org/multipage/semantics.html#the-style-element
 */
export interface HTMLStyleAttributes extends HTMLAttributes {
  blocking?: StringAttribute;
  media?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `table` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-table-element
 */
export interface HTMLTableAttributes extends HTMLAttributes {
  align?: StringAttribute;
  bgcolor?: StringAttribute;
  border?: StringAttribute;
  cellpadding?: StringAttribute;
  cellspacing?: StringAttribute;
  frame?: StringAttribute;
  rules?: StringAttribute;
  summary?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `tbody` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-tbody-element
 */
export interface HTMLTbodyAttributes extends HTMLAttributes {
  align?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  valign?: StringAttribute;
}

/**
 * Attributes for the HTML `td` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-td-element
 */
export interface HTMLTdAttributes extends HTMLAttributes {
  abbr?: StringAttribute;
  align?: StringAttribute;
  axis?: StringAttribute;
  bgcolor?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  colspan?: NumberAttribute;
  headers?: StringAttribute;
  height?: NumberAttribute;
  nowrap?: BooleanAttribute;
  rowspan?: NumberAttribute;
  scope?: Omissible<"col" | "colgroup" | "row" | "rowgroup">;
  valign?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `template` element.
 * @see https://html.spec.whatwg.org/multipage/scripting.html#the-template-element
 */
export interface HTMLTemplateAttributes extends HTMLAttributes {
  shadowrootclonable?: BooleanAttribute;
  shadowrootcustomelementregistry?: BooleanAttribute;
  shadowrootdelegatesfocus?: BooleanAttribute;
  shadowrootmode?: Omissible<"closed" | "open">;
  shadowrootserializable?: BooleanAttribute;
}

/**
 * Attributes for the HTML `textarea` element.
 * @see https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element
 */
export interface HTMLTextareaAttributes extends HTMLAttributes {
  autocomplete?: StringAttribute;
  cols?: NumberAttribute;
  dirname?: StringAttribute;
  disabled?: BooleanAttribute;
  form?: StringAttribute;
  maxlength?: NumberAttribute;
  minlength?: NumberAttribute;
  name?: StringAttribute;
  placeholder?: StringAttribute;
  readonly?: BooleanAttribute;
  required?: BooleanAttribute;
  rows?: NumberAttribute;
  wrap?: Omissible<"hard" | "soft">;
}

/**
 * Attributes for the HTML `tfoot` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element
 */
export interface HTMLTfootAttributes extends HTMLAttributes {
  align?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  valign?: StringAttribute;
}

/**
 * Attributes for the HTML `th` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-th-element
 */
export interface HTMLThAttributes extends HTMLAttributes {
  abbr?: StringAttribute;
  align?: StringAttribute;
  axis?: StringAttribute;
  bgcolor?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  colspan?: NumberAttribute;
  headers?: StringAttribute;
  height?: NumberAttribute;
  nowrap?: BooleanAttribute;
  rowspan?: NumberAttribute;
  scope?: Omissible<"col" | "colgroup" | "row" | "rowgroup">;
  valign?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes for the HTML `thead` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-thead-element
 */
export interface HTMLTheadAttributes extends HTMLAttributes {
  align?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  valign?: StringAttribute;
}

/**
 * Attributes for the HTML `time` element.
 * @see https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element
 */
export interface HTMLTimeAttributes extends HTMLAttributes {
  datetime?: StringAttribute;
}

/**
 * Attributes for the HTML `tr` element.
 * @see https://html.spec.whatwg.org/multipage/tables.html#the-tr-element
 */
export interface HTMLTrAttributes extends HTMLAttributes {
  align?: StringAttribute;
  bgcolor?: StringAttribute;
  char?: StringAttribute;
  charoff?: StringAttribute;
  valign?: StringAttribute;
}

/**
 * Attributes for the HTML `track` element.
 * @see https://html.spec.whatwg.org/multipage/media.html#the-track-element
 */
export interface HTMLTrackAttributes extends HTMLAttributes {
  default?: BooleanAttribute;
  kind?: Omissible<TrackKind>;
  label?: StringAttribute;
  src?: StringAttribute;
  srclang?: StringAttribute;
}

/**
 * Attributes for the HTML `ul` element.
 * @see https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element
 */
export interface HTMLUlAttributes extends HTMLAttributes {
  compact?: BooleanAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the HTML `video` element.
 * @see https://html.spec.whatwg.org/multipage/media.html#video
 */
export interface HTMLVideoAttributes extends HTMLAttributes {
  autoplay?: BooleanAttribute;
  controls?: BooleanAttribute;
  controlslist?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  disableremoteplayback?: BooleanAttribute;
  height?: NumberAttribute;
  loop?: BooleanAttribute;
  muted?: BooleanAttribute;
  playsinline?: BooleanAttribute;
  poster?: StringAttribute;
  preload?: Omissible<"" | "auto" | "metadata" | "none">;
  src?: StringAttribute;
  width?: NumberAttribute;
}

/**
 * Attributes shared by SVG elements, using serialized case-sensitive
 * names. Event handlers and React aliases are absent.
 */
export interface SVGAttributes extends DataAttributes, AriaAttributes {
  children?: Renderable;
  about?: StringAttribute;
  "alignment-baseline"?: StringAttribute;
  "baseline-shift"?: SVGNumberAttribute;
  class?: StringAttribute;
  "clip-path"?: StringAttribute;
  "clip-rule"?: Omissible<"evenodd" | "inherit" | "nonzero">;
  color?: StringAttribute;
  "color-interpolation"?: StringAttribute;
  "color-interpolation-filters"?: Omissible<"auto" | "linearRGB" | "sRGB">;
  "color-rendering"?: StringAttribute;
  content?: StringAttribute;
  cursor?: StringAttribute;
  datatype?: StringAttribute;
  direction?: StringAttribute;
  display?: StringAttribute;
  "dominant-baseline"?: StringAttribute;
  fill?: StringAttribute;
  "fill-opacity"?: SVGNumberAttribute;
  "fill-rule"?: Omissible<"evenodd" | "inherit" | "nonzero">;
  filter?: StringAttribute;
  "flood-color"?: StringAttribute;
  "flood-opacity"?: SVGNumberAttribute;
  "font-family"?: StringAttribute;
  "font-size"?: SVGNumberAttribute;
  "font-size-adjust"?: SVGNumberAttribute;
  "font-stretch"?: StringAttribute;
  "font-style"?: StringAttribute;
  "font-variant"?: StringAttribute;
  "font-weight"?: SVGNumberAttribute;
  "glyph-orientation-horizontal"?: StringAttribute;
  "glyph-orientation-vertical"?: StringAttribute;
  id?: StringAttribute;
  "image-rendering"?: StringAttribute;
  lang?: StringAttribute;
  "letter-spacing"?: SVGNumberAttribute;
  "lighting-color"?: StringAttribute;
  "marker-end"?: StringAttribute;
  "marker-mid"?: StringAttribute;
  "marker-start"?: StringAttribute;
  mask?: StringAttribute;
  opacity?: SVGNumberAttribute;
  overflow?: StringAttribute;
  "paint-order"?: StringAttribute;
  "pointer-events"?: StringAttribute;
  property?: StringAttribute;
  rel?: StringAttribute;
  resource?: StringAttribute;
  rev?: StringAttribute;
  "shape-rendering"?: StringAttribute;
  "stop-color"?: StringAttribute;
  "stop-opacity"?: SVGNumberAttribute;
  stroke?: StringAttribute;
  "stroke-dasharray"?: SVGNumberAttribute;
  "stroke-dashoffset"?: SVGNumberAttribute;
  "stroke-linecap"?: Omissible<"butt" | "inherit" | "round" | "square">;
  "stroke-linejoin"?: Omissible<"bevel" | "inherit" | "miter" | "round">;
  "stroke-miterlimit"?: SVGNumberAttribute;
  "stroke-opacity"?: SVGNumberAttribute;
  "stroke-width"?: SVGNumberAttribute;
  style?: StringAttribute;
  tabindex?: StringAttribute;
  "text-anchor"?: Omissible<"end" | "inherit" | "middle" | "start">;
  "text-decoration"?: StringAttribute;
  "text-overflow"?: StringAttribute;
  "text-rendering"?: StringAttribute;
  transform?: StringAttribute;
  typeof?: StringAttribute;
  "unicode-bidi"?: StringAttribute;
  "vector-effect"?: StringAttribute;
  visibility?: StringAttribute;
  "white-space"?: StringAttribute;
  "word-spacing"?: SVGNumberAttribute;
  "writing-mode"?: StringAttribute;
  "xml:base"?: StringAttribute;
  "xml:lang"?: StringAttribute;
  "xml:space"?: Omissible<"default" | "preserve">;
}

/**
 * Attributes for the SVG `a` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/linking.html#elementdef-a
 */
export interface SVGAAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  download?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  href?: StringAttribute;
  hreflang?: StringAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  ping?: StringAttribute;
  referrerpolicy?: Omissible<ReferrerPolicy>;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
  target?: StringAttribute;
  type?: StringAttribute;
  "xlink:actuate"?: StringAttribute;
  "xlink:arcrole"?: StringAttribute;
  "xlink:href"?: StringAttribute;
  "xlink:role"?: StringAttribute;
  "xlink:show"?: StringAttribute;
  "xlink:title"?: StringAttribute;
  "xlink:type"?: StringAttribute;
}

/**
 * Attributes for the SVG `animate` element.
 * @see https://svgwg.org/specs/animations/#elementdef-animate
 */
export interface SVGAnimateAttributes extends SVGAttributes {
  accumulate?: Omissible<"none" | "sum">;
  additive?: Omissible<"replace" | "sum">;
  attributeName?: StringAttribute;
  attributeType?: StringAttribute;
  begin?: SVGNumberAttribute;
  by?: SVGNumberAttribute;
  calcMode?: Omissible<"discrete" | "linear" | "paced" | "spline">;
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  dur?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  end?: SVGNumberAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  from?: SVGNumberAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  keySplines?: StringAttribute;
  keyTimes?: StringAttribute;
  max?: SVGNumberAttribute;
  min?: SVGNumberAttribute;
  repeatCount?: SVGNumberAttribute | Omissible<"indefinite">;
  repeatDur?: SVGNumberAttribute | Omissible<"indefinite">;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  restart?: Omissible<"always" | "never" | "whenNotActive">;
  systemLanguage?: StringAttribute;
  to?: SVGNumberAttribute;
  values?: StringAttribute;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `animateMotion` element.
 * @see https://svgwg.org/specs/animations/#elementdef-animateMotion
 */
export interface SVGAnimateMotionAttributes extends SVGAttributes {
  accumulate?: Omissible<"none" | "sum">;
  additive?: Omissible<"replace" | "sum">;
  begin?: SVGNumberAttribute;
  by?: SVGNumberAttribute;
  calcMode?: Omissible<"discrete" | "linear" | "paced" | "spline">;
  dur?: SVGNumberAttribute;
  end?: SVGNumberAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  from?: SVGNumberAttribute;
  href?: StringAttribute;
  keyPoints?: StringAttribute;
  keySplines?: StringAttribute;
  keyTimes?: StringAttribute;
  max?: SVGNumberAttribute;
  min?: SVGNumberAttribute;
  origin?: SVGNumberAttribute;
  path?: StringAttribute;
  repeatCount?: SVGNumberAttribute | Omissible<"indefinite">;
  repeatDur?: SVGNumberAttribute | Omissible<"indefinite">;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  restart?: Omissible<"always" | "never" | "whenNotActive">;
  rotate?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
  to?: SVGNumberAttribute;
  values?: StringAttribute;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `animateTransform` element.
 * @see https://svgwg.org/specs/animations/#elementdef-animateTransform
 */
export interface SVGAnimateTransformAttributes extends SVGAttributes {
  accumulate?: Omissible<"none" | "sum">;
  additive?: Omissible<"replace" | "sum">;
  attributeName?: StringAttribute;
  attributeType?: StringAttribute;
  begin?: SVGNumberAttribute;
  by?: SVGNumberAttribute;
  calcMode?: Omissible<"discrete" | "linear" | "paced" | "spline">;
  dur?: SVGNumberAttribute;
  end?: SVGNumberAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  from?: SVGNumberAttribute;
  href?: StringAttribute;
  keySplines?: StringAttribute;
  keyTimes?: StringAttribute;
  max?: SVGNumberAttribute;
  min?: SVGNumberAttribute;
  repeatCount?: SVGNumberAttribute | Omissible<"indefinite">;
  repeatDur?: SVGNumberAttribute | Omissible<"indefinite">;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  restart?: Omissible<"always" | "never" | "whenNotActive">;
  systemLanguage?: StringAttribute;
  to?: SVGNumberAttribute;
  type?: StringAttribute;
  values?: StringAttribute;
}

/**
 * Attributes for the SVG `circle` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-circle
 */
export interface SVGCircleAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  cx?: SVGNumberAttribute;
  cy?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  r?: SVGNumberAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `clipPath` element.
 * @see https://drafts.csswg.org/css-masking-1/#elementdef-clippath
 */
export interface SVGClipPathAttributes extends SVGAttributes {
  clip?: StringAttribute;
  clipPathUnits?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  kerning?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `defs` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-defs
 */
export interface SVGDefsAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  kerning?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `desc` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-desc
 */
export interface SVGDescAttributes extends SVGAttributes {
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `ellipse` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-ellipse
 */
export interface SVGEllipseAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  cx?: SVGNumberAttribute;
  cy?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  rx?: SVGNumberAttribute;
  ry?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `feBlend` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feblend
 */
export interface SVGFeBlendAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  in2?: StringAttribute;
  kerning?: StringAttribute;
  mode?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feColorMatrix` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fecolormatrix
 */
export interface SVGFeColorMatrixAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  type?: StringAttribute;
  values?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feComponentTransfer` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fecomponenttransfer
 */
export interface SVGFeComponentTransferAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feComposite` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fecomposite
 */
export interface SVGFeCompositeAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  in2?: StringAttribute;
  k1?: SVGNumberAttribute;
  k2?: SVGNumberAttribute;
  k3?: SVGNumberAttribute;
  k4?: SVGNumberAttribute;
  kerning?: StringAttribute;
  operator?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feConvolveMatrix` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feconvolvematrix
 */
export interface SVGFeConvolveMatrixAttributes extends SVGAttributes {
  bias?: SVGNumberAttribute;
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  divisor?: SVGNumberAttribute;
  edgeMode?: Omissible<"duplicate" | "none" | "wrap">;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kernelMatrix?: StringAttribute;
  kernelUnitLength?: SVGNumberAttribute;
  kerning?: StringAttribute;
  order?: SVGNumberAttribute;
  preserveAlpha?: BooleanishAttribute;
  result?: StringAttribute;
  targetX?: SVGNumberAttribute;
  targetY?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feDiffuseLighting` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fediffuselighting
 */
export interface SVGFeDiffuseLightingAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  diffuseConstant?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kernelUnitLength?: SVGNumberAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  surfaceScale?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feDisplacementMap` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fedisplacementmap
 */
export interface SVGFeDisplacementMapAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  in2?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  scale?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  xChannelSelector?: Omissible<"A" | "B" | "G" | "R">;
  y?: SVGNumberAttribute;
  yChannelSelector?: Omissible<"A" | "B" | "G" | "R">;
}

/**
 * Attributes for the SVG `feDistantLight` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fedistantlight
 */
export interface SVGFeDistantLightAttributes extends SVGAttributes {
  azimuth?: SVGNumberAttribute;
  elevation?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feDropShadow` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fedropshadow
 */
export interface SVGFeDropShadowAttributes extends SVGAttributes {
  dx?: SVGNumberAttribute;
  dy?: SVGNumberAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  result?: StringAttribute;
  stdDeviation?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feFlood` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feflood
 */
export interface SVGFeFloodAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feFuncA` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fefunca
 */
export interface SVGFeFuncAAttributes extends SVGAttributes {
  amplitude?: SVGNumberAttribute;
  exponent?: SVGNumberAttribute;
  intercept?: SVGNumberAttribute;
  offset?: SVGNumberAttribute;
  slope?: SVGNumberAttribute;
  tableValues?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the SVG `feFuncB` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fefuncb
 */
export interface SVGFeFuncBAttributes extends SVGAttributes {
  amplitude?: SVGNumberAttribute;
  exponent?: SVGNumberAttribute;
  intercept?: SVGNumberAttribute;
  offset?: SVGNumberAttribute;
  slope?: SVGNumberAttribute;
  tableValues?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the SVG `feFuncG` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fefuncg
 */
export interface SVGFeFuncGAttributes extends SVGAttributes {
  amplitude?: SVGNumberAttribute;
  exponent?: SVGNumberAttribute;
  intercept?: SVGNumberAttribute;
  offset?: SVGNumberAttribute;
  slope?: SVGNumberAttribute;
  tableValues?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the SVG `feFuncR` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fefuncr
 */
export interface SVGFeFuncRAttributes extends SVGAttributes {
  amplitude?: SVGNumberAttribute;
  exponent?: SVGNumberAttribute;
  intercept?: SVGNumberAttribute;
  offset?: SVGNumberAttribute;
  slope?: SVGNumberAttribute;
  tableValues?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the SVG `feGaussianBlur` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fegaussianblur
 */
export interface SVGFeGaussianBlurAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  edgeMode?: Omissible<"duplicate" | "none" | "wrap">;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  stdDeviation?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feImage` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feimage
 */
export interface SVGFeImageAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  height?: SVGNumberAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  preserveAspectRatio?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feMerge` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-femerge
 */
export interface SVGFeMergeAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feMergeNode` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-femergenode
 */
export interface SVGFeMergeNodeAttributes extends SVGAttributes {
  in?: StringAttribute;
}

/**
 * Attributes for the SVG `feMorphology` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-femorphology
 */
export interface SVGFeMorphologyAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  operator?: StringAttribute;
  radius?: SVGNumberAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feOffset` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feoffset
 */
export interface SVGFeOffsetAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  dx?: SVGNumberAttribute;
  dy?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `fePointLight` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fepointlight
 */
export interface SVGFePointLightAttributes extends SVGAttributes {
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
  z?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feSpecularLighting` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fespecularlighting
 */
export interface SVGFeSpecularLightingAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kernelUnitLength?: SVGNumberAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  specularConstant?: SVGNumberAttribute;
  specularExponent?: SVGNumberAttribute;
  surfaceScale?: SVGNumberAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feSpotLight` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fespotlight
 */
export interface SVGFeSpotLightAttributes extends SVGAttributes {
  limitingConeAngle?: SVGNumberAttribute;
  pointsAtX?: SVGNumberAttribute;
  pointsAtY?: SVGNumberAttribute;
  pointsAtZ?: SVGNumberAttribute;
  specularExponent?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
  z?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feTile` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-fetile
 */
export interface SVGFeTileAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  in?: StringAttribute;
  kerning?: StringAttribute;
  result?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `feTurbulence` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-feturbulence
 */
export interface SVGFeTurbulenceAttributes extends SVGAttributes {
  baseFrequency?: SVGNumberAttribute;
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  numOctaves?: SVGNumberAttribute;
  result?: StringAttribute;
  seed?: SVGNumberAttribute;
  stitchTiles?: Omissible<"noStitch" | "stitch">;
  type?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `filter` element.
 * @see https://drafts.csswg.org/filter-effects-1/#elementdef-filter
 */
export interface SVGFilterAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  filterRes?: StringAttribute;
  filterUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  primitiveUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `foreignObject` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/embedded.html#elementdef-foreignObject
 */
export interface SVGForeignObjectAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `g` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-g
 */
export interface SVGGAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `image` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/embedded.html#elementdef-image
 */
export interface SVGImageAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  crossorigin?: Omissible<CrossOrigin>;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  height?: SVGNumberAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  preserveAspectRatio?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
  type?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  "xlink:href"?: StringAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `line` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-line
 */
export interface SVGLineAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
  x1?: SVGNumberAttribute;
  x2?: SVGNumberAttribute;
  y1?: SVGNumberAttribute;
  y2?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `linearGradient` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/pservers.html#elementdef-linearGradient
 */
export interface SVGLinearGradientAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  gradientTransform?: StringAttribute;
  gradientUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  href?: StringAttribute;
  kerning?: StringAttribute;
  spreadMethod?: Omissible<"pad" | "reflect" | "repeat">;
  x1?: SVGNumberAttribute;
  x2?: SVGNumberAttribute;
  "xlink:href"?: StringAttribute;
  y1?: SVGNumberAttribute;
  y2?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `marker` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/painting.html#elementdef-marker
 */
export interface SVGMarkerAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  kerning?: StringAttribute;
  markerHeight?: SVGNumberAttribute;
  markerUnits?: Omissible<"strokeWidth" | "userSpaceOnUse">;
  markerWidth?: SVGNumberAttribute;
  orient?: SVGNumberAttribute | Omissible<"auto" | "auto-start-reverse">;
  preserveAspectRatio?: StringAttribute;
  refX?: SVGNumberAttribute;
  refY?: SVGNumberAttribute;
  viewBox?: StringAttribute;
}

/**
 * Attributes for the SVG `mask` element.
 * @see https://drafts.csswg.org/css-masking-1/#elementdef-mask
 */
export interface SVGMaskAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  maskContentUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  maskUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  systemLanguage?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `metadata` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-metadata
 */
export interface SVGMetadataAttributes extends SVGAttributes {
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `mpath` element.
 * @see https://svgwg.org/specs/animations/#elementdef-mpath
 */
export interface SVGMpathAttributes extends SVGAttributes {
  externalResourcesRequired?: BooleanishAttribute;
  href?: StringAttribute;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `path` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/paths.html#elementdef-path
 */
export interface SVGPathAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  d?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `pattern` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/pservers.html#elementdef-pattern
 */
export interface SVGPatternAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  height?: SVGNumberAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  patternContentUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  patternTransform?: StringAttribute;
  patternUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  preserveAspectRatio?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  systemLanguage?: StringAttribute;
  viewBox?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  "xlink:href"?: StringAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `polygon` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-polygon
 */
export interface SVGPolygonAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  points?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `polyline` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-polyline
 */
export interface SVGPolylineAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  points?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `radialGradient` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/pservers.html#elementdef-radialGradient
 */
export interface SVGRadialGradientAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  cx?: SVGNumberAttribute;
  cy?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  fr?: SVGNumberAttribute;
  fx?: SVGNumberAttribute;
  fy?: SVGNumberAttribute;
  gradientTransform?: StringAttribute;
  gradientUnits?: Omissible<"objectBoundingBox" | "userSpaceOnUse">;
  href?: StringAttribute;
  kerning?: StringAttribute;
  r?: SVGNumberAttribute;
  spreadMethod?: Omissible<"pad" | "reflect" | "repeat">;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `rect` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/shapes.html#elementdef-rect
 */
export interface SVGRectAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  pathLength?: SVGNumberAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  rx?: SVGNumberAttribute;
  ry?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `script` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/interact.html#elementdef-script
 */
export interface SVGScriptAttributes extends SVGAttributes {
  crossorigin?: Omissible<CrossOrigin>;
  externalResourcesRequired?: BooleanishAttribute;
  href?: StringAttribute;
  type?: StringAttribute;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `set` element.
 * @see https://svgwg.org/specs/animations/#elementdef-set
 */
export interface SVGSetAttributes extends SVGAttributes {
  attributeName?: StringAttribute;
  attributeType?: StringAttribute;
  begin?: SVGNumberAttribute;
  dur?: SVGNumberAttribute;
  end?: SVGNumberAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  href?: StringAttribute;
  max?: SVGNumberAttribute;
  min?: SVGNumberAttribute;
  repeatCount?: SVGNumberAttribute | Omissible<"indefinite">;
  repeatDur?: SVGNumberAttribute | Omissible<"indefinite">;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  restart?: Omissible<"always" | "never" | "whenNotActive">;
  systemLanguage?: StringAttribute;
  to?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `stop` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/pservers.html#elementdef-stop
 */
export interface SVGStopAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  kerning?: StringAttribute;
  offset?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `style` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/styling.html#elementdef-style
 */
export interface SVGStyleAttributes extends SVGAttributes {
  media?: StringAttribute;
  title?: StringAttribute;
  type?: StringAttribute;
}

/**
 * Attributes for the SVG `svg` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-svg
 */
export interface SVGSvgAttributes extends SVGAttributes {
  baseProfile?: StringAttribute;
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  contentScriptType?: StringAttribute;
  contentStyleType?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  playbackOrder?: StringAttribute;
  playbackorder?: StringAttribute;
  preserveAspectRatio?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  snapshotTime?: StringAttribute;
  syncBehaviorDefault?: StringAttribute;
  syncToleranceDefault?: StringAttribute;
  systemLanguage?: StringAttribute;
  timelineBegin?: StringAttribute;
  timelinebegin?: StringAttribute;
  version?: StringAttribute;
  viewBox?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  xmlns?: StringAttribute;
  "xmlns:xlink"?: StringAttribute;
  y?: SVGNumberAttribute;
  zoomAndPan?: Omissible<"disable" | "magnify">;
}

/**
 * Attributes for the SVG `switch` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-switch
 */
export interface SVGSwitchAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `symbol` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-symbol
 */
export interface SVGSymbolAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  height?: SVGNumberAttribute;
  kerning?: StringAttribute;
  preserveAspectRatio?: StringAttribute;
  refX?: SVGNumberAttribute;
  refY?: SVGNumberAttribute;
  viewBox?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `text` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/text.html#elementdef-text
 */
export interface SVGTextAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  dx?: SVGNumberAttribute;
  dy?: SVGNumberAttribute;
  editable?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  lengthAdjust?: Omissible<"spacing" | "spacingAndGlyphs">;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  rotate?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
  textLength?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `textPath` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/text.html#elementdef-textPath
 */
export interface SVGTextPathAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  lengthAdjust?: Omissible<"spacing" | "spacingAndGlyphs">;
  method?: StringAttribute;
  path?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  side?: StringAttribute;
  spacing?: Omissible<"auto" | "exact">;
  startOffset?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
  textLength?: SVGNumberAttribute;
  "xlink:href"?: StringAttribute;
}

/**
 * Attributes for the SVG `title` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-title
 */
export interface SVGTitleAttributes extends SVGAttributes {
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
}

/**
 * Attributes for the SVG `tspan` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/text.html#elementdef-tspan
 */
export interface SVGTspanAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  dx?: SVGNumberAttribute;
  dy?: SVGNumberAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  kerning?: StringAttribute;
  lengthAdjust?: Omissible<"spacing" | "spacingAndGlyphs">;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  rotate?: SVGNumberAttribute;
  systemLanguage?: StringAttribute;
  textLength?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `use` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/struct.html#elementdef-use
 */
export interface SVGUseAttributes extends SVGAttributes {
  clip?: StringAttribute;
  "color-profile"?: StringAttribute;
  "enable-background"?: StringAttribute;
  externalResourcesRequired?: BooleanishAttribute;
  focusHighlight?: StringAttribute;
  focusable?: Omissible<"auto" | "false" | "true">;
  height?: SVGNumberAttribute;
  href?: StringAttribute;
  kerning?: StringAttribute;
  "nav-down"?: StringAttribute;
  "nav-down-left"?: StringAttribute;
  "nav-down-right"?: StringAttribute;
  "nav-left"?: StringAttribute;
  "nav-next"?: StringAttribute;
  "nav-prev"?: StringAttribute;
  "nav-right"?: StringAttribute;
  "nav-up"?: StringAttribute;
  "nav-up-left"?: StringAttribute;
  "nav-up-right"?: StringAttribute;
  requiredExtensions?: StringAttribute;
  requiredFeatures?: StringAttribute;
  requiredFonts?: StringAttribute;
  requiredFormats?: StringAttribute;
  systemLanguage?: StringAttribute;
  width?: SVGNumberAttribute;
  x?: SVGNumberAttribute;
  "xlink:href"?: StringAttribute;
  y?: SVGNumberAttribute;
}

/**
 * Attributes for the SVG `view` element.
 * @see https://w3c.github.io/svgwg/svg2-draft/linking.html#elementdef-view
 */
export interface SVGViewAttributes extends SVGAttributes {
  externalResourcesRequired?: BooleanishAttribute;
  preserveAspectRatio?: StringAttribute;
  viewBox?: StringAttribute;
  viewTarget?: StringAttribute;
  zoomAndPan?: Omissible<"disable" | "magnify">;
}

/** Serializable props accepted by hyphenated custom-element names. */
export interface CustomElementAttributes extends HTMLAttributes {
  [name: `${string}-${string}`]: AttributeValue;
}

/**
 * Types consumed internally by TypeScript's automatic JSX transform.
 *
 * @internal
 */
// deno-lint-ignore no-namespace
export namespace JSX {
  /** The immutable instruction value produced by a JSX expression. */
  export type Element = Html;

  /** Intrinsic names and server component functions accepted in JSX. */
  export type ElementType =
    | keyof IntrinsicElements
    | ((props: never) => Renderable);

  /** Identifies the component prop that receives nested JSX children. */
  export interface ElementChildrenAttribute {
    /** Property used by the transform for nested JSX children. */
    children: unknown;
  }

  /** HTML, SVG, and custom elements supported by the JSX runtime. */
  export interface IntrinsicElements {
    [tagName: `${string}-${string}`]: CustomElementAttributes;
    // A JSX tag cannot select types from its parent namespace. Names shared
    // by HTML and SVG therefore accept the attributes of either element.
    a: HTMLAAttributes | SVGAAttributes;
    abbr: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#acronym
     */
    acronym: HTMLAttributes;
    address: HTMLAttributes;
    animate: SVGAnimateAttributes;
    animateMotion: SVGAnimateMotionAttributes;
    animateTransform: SVGAnimateTransformAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#applet
     */
    applet: HTMLAppletAttributes;
    area: HTMLAreaAttributes;
    article: HTMLAttributes;
    aside: HTMLAttributes;
    audio: HTMLAudioAttributes;
    b: HTMLAttributes;
    base: HTMLBaseAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#basefont
     */
    basefont: HTMLBasefontAttributes;
    bdi: HTMLAttributes;
    bdo: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#bgsound
     */
    bgsound: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#big
     */
    big: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#blink
     */
    blink: HTMLAttributes;
    blockquote: HTMLBlockquoteAttributes;
    body: HTMLBodyAttributes;
    br: HTMLBrAttributes;
    button: HTMLButtonAttributes;
    canvas: HTMLCanvasAttributes;
    caption: HTMLCaptionAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#center
     */
    center: HTMLAttributes;
    circle: SVGCircleAttributes;
    cite: HTMLAttributes;
    clipPath: SVGClipPathAttributes;
    code: HTMLAttributes;
    col: HTMLColAttributes;
    colgroup: HTMLColgroupAttributes;
    data: HTMLDataAttributes;
    datalist: HTMLAttributes;
    dd: HTMLAttributes;
    defs: SVGDefsAttributes;
    del: HTMLDelAttributes;
    desc: SVGDescAttributes;
    details: HTMLDetailsAttributes;
    dfn: HTMLAttributes;
    dialog: HTMLDialogAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#dir
     */
    dir: HTMLDirAttributes;
    div: HTMLDivAttributes;
    dl: HTMLDlAttributes;
    dt: HTMLAttributes;
    ellipse: SVGEllipseAttributes;
    em: HTMLAttributes;
    embed: HTMLEmbedAttributes;
    feBlend: SVGFeBlendAttributes;
    feColorMatrix: SVGFeColorMatrixAttributes;
    feComponentTransfer: SVGFeComponentTransferAttributes;
    feComposite: SVGFeCompositeAttributes;
    feConvolveMatrix: SVGFeConvolveMatrixAttributes;
    feDiffuseLighting: SVGFeDiffuseLightingAttributes;
    feDisplacementMap: SVGFeDisplacementMapAttributes;
    feDistantLight: SVGFeDistantLightAttributes;
    feDropShadow: SVGFeDropShadowAttributes;
    feFlood: SVGFeFloodAttributes;
    feFuncA: SVGFeFuncAAttributes;
    feFuncB: SVGFeFuncBAttributes;
    feFuncG: SVGFeFuncGAttributes;
    feFuncR: SVGFeFuncRAttributes;
    feGaussianBlur: SVGFeGaussianBlurAttributes;
    feImage: SVGFeImageAttributes;
    feMerge: SVGFeMergeAttributes;
    feMergeNode: SVGFeMergeNodeAttributes;
    feMorphology: SVGFeMorphologyAttributes;
    feOffset: SVGFeOffsetAttributes;
    fePointLight: SVGFePointLightAttributes;
    feSpecularLighting: SVGFeSpecularLightingAttributes;
    feSpotLight: SVGFeSpotLightAttributes;
    feTile: SVGFeTileAttributes;
    feTurbulence: SVGFeTurbulenceAttributes;
    fieldset: HTMLFieldsetAttributes;
    figcaption: HTMLAttributes;
    figure: HTMLAttributes;
    filter: SVGFilterAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#font
     */
    font: HTMLFontAttributes;
    footer: HTMLAttributes;
    foreignObject: SVGForeignObjectAttributes;
    form: HTMLFormAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#frame
     */
    frame: HTMLFrameAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#frameset
     */
    frameset: HTMLFramesetAttributes;
    g: SVGGAttributes;
    h1: HTMLH1Attributes;
    h2: HTMLH2Attributes;
    h3: HTMLH3Attributes;
    h4: HTMLH4Attributes;
    h5: HTMLH5Attributes;
    h6: HTMLH6Attributes;
    head: HTMLHeadAttributes;
    header: HTMLAttributes;
    hgroup: HTMLAttributes;
    hr: HTMLHrAttributes;
    html: HTMLHtmlAttributes;
    i: HTMLAttributes;
    iframe: HTMLIframeAttributes;
    image: SVGImageAttributes;
    img: HTMLImgAttributes;
    input: HTMLInputAttributes;
    ins: HTMLInsAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#isindex
     */
    isindex: HTMLIsindexAttributes;
    kbd: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#keygen
     */
    keygen: HTMLAttributes;
    label: HTMLLabelAttributes;
    legend: HTMLLegendAttributes;
    li: HTMLLiAttributes;
    line: SVGLineAttributes;
    linearGradient: SVGLinearGradientAttributes;
    link: HTMLLinkAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#listing
     */
    listing: HTMLAttributes;
    main: HTMLAttributes;
    map: HTMLMapAttributes;
    mark: HTMLAttributes;
    marker: SVGMarkerAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#the-marquee-element
     */
    marquee: HTMLAttributes;
    mask: SVGMaskAttributes;
    menu: HTMLMenuAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#menuitem
     */
    menuitem: HTMLAttributes;
    meta: HTMLMetaAttributes;
    metadata: SVGMetadataAttributes;
    meter: HTMLMeterAttributes;
    mpath: SVGMpathAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#multicol
     */
    multicol: HTMLAttributes;
    nav: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#nextid
     */
    nextid: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#nobr
     */
    nobr: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#noembed
     */
    noembed: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#noframes
     */
    noframes: HTMLAttributes;
    noscript: HTMLAttributes;
    object: HTMLObjectAttributes;
    ol: HTMLOlAttributes;
    optgroup: HTMLOptgroupAttributes;
    option: HTMLOptionAttributes;
    output: HTMLOutputAttributes;
    p: HTMLPAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#param
     */
    param: HTMLParamAttributes;
    path: SVGPathAttributes;
    pattern: SVGPatternAttributes;
    picture: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#plaintext
     */
    plaintext: HTMLAttributes;
    polygon: SVGPolygonAttributes;
    polyline: SVGPolylineAttributes;
    pre: HTMLPreAttributes;
    progress: HTMLProgressAttributes;
    q: HTMLQAttributes;
    radialGradient: SVGRadialGradientAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#rb
     */
    rb: HTMLAttributes;
    rect: SVGRectAttributes;
    rp: HTMLAttributes;
    rt: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#rtc
     */
    rtc: HTMLAttributes;
    ruby: HTMLAttributes;
    s: HTMLAttributes;
    samp: HTMLAttributes;
    script: HTMLScriptAttributes | SVGScriptAttributes;
    search: HTMLAttributes;
    section: HTMLAttributes;
    select: HTMLSelectAttributes;
    selectedcontent: HTMLAttributes;
    set: SVGSetAttributes;
    slot: HTMLSlotAttributes;
    small: HTMLAttributes;
    source: HTMLSourceAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#spacer
     */
    spacer: HTMLAttributes;
    span: HTMLAttributes;
    stop: SVGStopAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#strike
     */
    strike: HTMLAttributes;
    strong: HTMLAttributes;
    style: HTMLStyleAttributes | SVGStyleAttributes;
    sub: HTMLAttributes;
    summary: HTMLAttributes;
    sup: HTMLAttributes;
    svg: SVGSvgAttributes;
    switch: SVGSwitchAttributes;
    symbol: SVGSymbolAttributes;
    table: HTMLTableAttributes;
    tbody: HTMLTbodyAttributes;
    td: HTMLTdAttributes;
    template: HTMLTemplateAttributes;
    text: SVGTextAttributes;
    textPath: SVGTextPathAttributes;
    textarea: HTMLTextareaAttributes;
    tfoot: HTMLTfootAttributes;
    th: HTMLThAttributes;
    thead: HTMLTheadAttributes;
    time: HTMLTimeAttributes;
    title: HTMLAttributes | SVGTitleAttributes;
    tr: HTMLTrAttributes;
    track: HTMLTrackAttributes;
    tspan: SVGTspanAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#tt
     */
    tt: HTMLAttributes;
    u: HTMLAttributes;
    ul: HTMLUlAttributes;
    use: SVGUseAttributes;
    var: HTMLAttributes;
    video: HTMLVideoAttributes;
    view: SVGViewAttributes;
    wbr: HTMLAttributes;
    /**
     * @deprecated Obsolete HTML element retained for migration.
     * @see https://html.spec.whatwg.org/multipage/obsolete.html#xmp
     */
    xmp: HTMLAttributes;
  }
}
